////////////////////////////////////////////////////////////////////////////////
// Copyright © 2022 xx foundation                                             //
//                                                                            //
// Use of this source code is governed by a license that can be found in the  //
// LICENSE file.                                                              //
////////////////////////////////////////////////////////////////////////////////

package region

import "strings"

// GetCountryBin return the bin for the given country alpha-2 code.
func GetCountryBin(countryCode string) (GeoBin, bool) {
	cleaned := strings.ToUpper(countryCode)
	bin, exists := countryBins[cleaned]
	return bin, exists
}

// GetCountryList returns a list of all country alpha-2 codes.
func GetCountryList() []string {
	list := make([]string, 0, len(countryBins))

	for code := range countryBins {
		list = append(list, code)
	}

	return list
}

// GetCountryBins returns a copy of the countryBins map.
func GetCountryBins() map[string]GeoBin {
	// Create the target map
	targetMap := make(map[string]GeoBin)

	// Copy from the original map to the target map
	for key, value := range countryBins {
		targetMap[key] = value
	}
	return targetMap
}

// CountryLen returns the number of countries in the countryBins list.
func CountryLen() int {
	return len(countryBins)
}

// countryBins maps country alpha-2 codes to their regional bin.
var countryBins = map[string]GeoBin{
	"AQ": NorthAmerica,
	"MX": NorthAmerica,
	"CA": NorthAmerica,
	"US": NorthAmerica,
	"UM": NorthAmerica,
	"AI": SouthAndCentralAmerica,
	"AG": SouthAndCentralAmerica,
	"AR": SouthAndCentralAmerica,
	"BS": SouthAndCentralAmerica,
	"UY": SouthAndCentralAmerica,
	"BB": SouthAndCentralAmerica,
	"BR": SouthAndCentralAmerica,
	"PE": SouthAndCentralAmerica,
	"BZ": SouthAndCentralAmerica,
	"CL": SouthAndCentralAmerica,
	"BM": SouthAndCentralAmerica,
	"EC": SouthAndCentralAmerica,
	"BO": SouthAndCentralAmerica,
	"GY": SouthAndCentralAmerica,
	"BQ": SouthAndCentralAmerica,
	"GF": SouthAndCentralAmerica,
	"SR": SouthAndCentralAmerica,
	"PY": SouthAndCentralAmerica,
	"KY": SouthAndCentralAmerica,
	"CO": SouthAndCentralAmerica,
	"NI": SouthAndCentralAmerica,
	"PR": SouthAndCentralAmerica,
	"CR": SouthAndCentralAmerica,
	"CU": SouthAndCentralAmerica,
	"CW": SouthAndCentralAmerica,
	"DM": SouthAndCentralAmerica,
	"DO": SouthAndCentralAmerica,
	"SV": SouthAndCentralAmerica,
	"GT": SouthAndCentralAmerica,
	"FK": SouthAndCentralAmerica,
	"JM": SouthAndCentralAmerica,
	"PA": SouthAndCentralAmerica,
	"VE": SouthAndCentralAmerica,
	"VG": SouthAndCentralAmerica,
	"VI": SouthAndCentralAmerica,
	"HT": SouthAndCentralAmerica,
	"HN": SouthAndCentralAmerica,
	"GL": SouthAndCentralAmerica,
	"GD": SouthAndCentralAmerica,
	"TC": SouthAndCentralAmerica,
	"TT": SouthAndCentralAmerica,
	"GS": SouthAndCentralAmerica,
	"MS": SouthAndCentralAmerica,
	"SX": SouthAndCentralAmerica,
	"GP": SouthAndCentralAmerica,
	"MQ": SouthAndCentralAmerica,
	"LC": SouthAndCentralAmerica,
	"KN": SouthAndCentralAmerica,
	"PM": SouthAndCentralAmerica,
	"BL": SouthAndCentralAmerica,
	"VC": SouthAndCentralAmerica,
	"AW": SouthAndCentralAmerica,
	"MF": SouthAndCentralAmerica,
	"AD": WesternEurope,
	"GB": WesternEurope,
	"ES": WesternEurope,
	"PT": WesternEurope,
	"NL": WesternEurope,
	"FR": WesternEurope,
	"IE": WesternEurope,
	"FO": WesternEurope,
	"IS": WesternEurope,
	"GI": WesternEurope,
	"MC": WesternEurope,
	"GG": WesternEurope,
	"JE": WesternEurope,
	"IM": WesternEurope,
	"BE": WesternEurope,
	"LU": WesternEurope,
	"AT": CentralEurope,
	"PL": CentralEurope,
	"NO": CentralEurope,
	"MT": CentralEurope,
	"DK": CentralEurope,
	"SE": CentralEurope,
	"CH": CentralEurope,
	"SK": CentralEurope,
	"SI": CentralEurope,
	"IT": CentralEurope,
	"DE": CentralEurope,
	"HU": CentralEurope,
	"LI": CentralEurope,
	"SJ": CentralEurope,
	"SM": CentralEurope,
	"VA": CentralEurope,
	"CZ": CentralEurope,
	"AX": EasternEurope,
	"AL": EasternEurope,
	"BY": EasternEurope,
	"UA": EasternEurope,
	"BA": EasternEurope,
	"LT": EasternEurope,
	"LV": EasternEurope,
	"BG": EasternEurope,
	"MD": EasternEurope,
	"HR": EasternEurope,
	"FI": EasternEurope,
	"CY": EasternEurope,
	"RO": EasternEurope,
	"EE": EasternEurope,
	"GR": EasternEurope,
	"ME": EasternEurope,
	"RS": EasternEurope,
	"MK": EasternEurope,
	"GE": EasternEurope,
	"AM": MiddleEast,
	"AZ": MiddleEast,
	"BH": MiddleEast,
	"TR": MiddleEast,
	"SA": MiddleEast,
	"AE": MiddleEast,
	"IQ": MiddleEast,
	"QA": MiddleEast,
	"YE": MiddleEast,
	"IL": MiddleEast,
	"JO": MiddleEast,
	"KW": MiddleEast,
	"PS": MiddleEast,
	"SY": MiddleEast,
	"IR": MiddleEast,
	"LB": MiddleEast,
	"OM": MiddleEast,
	"DZ": NorthernAfrica,
	"BJ": NorthernAfrica,
	"BF": NorthernAfrica,
	"CV": NorthernAfrica,
	"TD": NorthernAfrica,
	"SN": NorthernAfrica,
	"CI": NorthernAfrica,
	"ML": NorthernAfrica,
	"NE": NorthernAfrica,
	"DJ": NorthernAfrica,
	"EG": NorthernAfrica,
	"ET": NorthernAfrica,
	"GM": NorthernAfrica,
	"GH": NorthernAfrica,
	"ER": NorthernAfrica,
	"LR": NorthernAfrica,
	"LY": NorthernAfrica,
	"SL": NorthernAfrica,
	"TN": NorthernAfrica,
	"TG": NorthernAfrica,
	"EH": NorthernAfrica,
	"SD": NorthernAfrica,
	"MA": NorthernAfrica,
	"MR": NorthernAfrica,
	"GN": NorthernAfrica,
	"GW": NorthernAfrica,
	"AO": SouthernAfrica,
	"ZA": SouthernAfrica,
	"CM": SouthernAfrica,
	"RW": SouthernAfrica,
	"CG": SouthernAfrica,
	"CD": SouthernAfrica,
	"SO": SouthernAfrica,
	"ZM": SouthernAfrica,
	"ZW": SouthernAfrica,
	"UG": SouthernAfrica,
	"GA": SouthernAfrica,
	"GQ": SouthernAfrica,
	"SZ": SouthernAfrica,
	"BW": SouthernAfrica,
	"MG": SouthernAfrica,
	"TZ": SouthernAfrica,
	"NA": SouthernAfrica,
	"SS": SouthernAfrica,
	"MW": SouthernAfrica,
	"BI": SouthernAfrica,
	"MZ": SouthernAfrica,
	"KE": SouthernAfrica,
	"BV": SouthernAfrica,
	"CF": SouthernAfrica,
	"KM": SouthernAfrica,
	"NG": SouthernAfrica,
	"MU": SouthernAfrica,
	"SC": SouthernAfrica,
	"LS": SouthernAfrica,
	"YT": SouthernAfrica,
	"ST": SouthernAfrica,
	"RE": SouthernAfrica,
	"SH": SouthernAfrica,
	"RU": Russia,
	"BD": EasternAsia,
	"TH": EasternAsia,
	"BT": EasternAsia,
	"JP": EasternAsia,
	"KH": EasternAsia,
	"CN": EasternAsia,
	"MY": EasternAsia,
	"VN": EasternAsia,
	"NP": EasternAsia,
	"KP": EasternAsia,
	"KR": EasternAsia,
	"SG": EasternAsia,
	"MM": EasternAsia,
	"MN": EasternAsia,
	"HK": EasternAsia,
	"MO": EasternAsia,
	"LA": EasternAsia,
	"KZ": WesternAsia,
	"AF": WesternAsia,
	"TM": WesternAsia,
	"UZ": WesternAsia,
	"PK": WesternAsia,
	"KG": WesternAsia,
	"TJ": WesternAsia,
	"IN": WesternAsia,
	"LK": WesternAsia,
	"IO": WesternAsia,
	"MV": WesternAsia,
	"TW": Oceania,
	"AU": Oceania,
	"PG": Oceania,
	"FJ": Oceania,
	"TL": Oceania,
	"ID": Oceania,
	"PH": Oceania,
	"SB": Oceania,
	"NC": Oceania,
	"NZ": Oceania,
	"VU": Oceania,
	"TV": Oceania,
	"TK": Oceania,
	"AS": Oceania,
	"WF": Oceania,
	"TO": Oceania,
	"NU": Oceania,
	"CK": Oceania,
	"PF": Oceania,
	"PN": Oceania,
	"WS": Oceania,
	"PW": Oceania,
	"GU": Oceania,
	"NR": Oceania,
	"KI": Oceania,
	"CX": Oceania,
	"CC": Oceania,
	"NF": Oceania,
	"MH": Oceania,
	"FM": Oceania,
	"MP": Oceania,
	"HM": Oceania,
	"TF": Oceania,
	"BN": Oceania,
}
